### Data Transformation
- Once your data is clean, the next step is to reshape, reformat, and reorder it as
needed for analysis. Pandas gives you plenty of flexible tools to do this

#### Sorting & Ranking

##### Sort by Values
- ```df.sort_values("Age")``` # Ascending sort
- ```df.sort_values("Age", ascending=False)``` # Descending
- ```df.sort_values(["Age", "Salary"])``` # Sort by multiple columns

In [1]:
import pandas as pd
df = pd.read_csv('05_data.csv')

In [2]:
df2 = df.sort_values("Year")
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

### Reset Index
- If  you want the index to start from 0 and be sequential, you can reset it using
reset_index()

In [3]:
df2.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
5,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
6,7,Hrithik Roshan,War,2019,Action,475,6.5
7,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [4]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [5]:
df2.reset_index(drop=True, inplace=True) # Reset the index and drop the old index
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
5,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

### Sort by Index

- ```df.sort_index()```
- The df.sort_index() function is used to sort the DataFrame based on its index
values. If the index is not in a sequential order (e.g., you have dropped rows or
performed other operations that change the index), you can use sort_index() to
restore it to a sorted order. ### Ranking The .rank() function in pandas is used to
assign ranks to numeric values in a column, like scores or points. By default, it gives
the average rank to tied values, which can result in decimal numbers. For example,
if two people share the top score, they both get a rank of 1.5. You can customize
the ranking behavior using the method parameter. One useful option is
method=‘dense’, which assigns the same rank to ties but doesn’t leave gaps in the
ranking sequence. This is helpful when you want a clean, consecutive ranking
system without skips

In [6]:
df.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

### Ranking
- The .rank() function in pandas is used to assign ranks to numeric values in a column, like scores or points. By default, it gives the average rank to tied values, which can result in decimal numbers. For example, if two people share the top score, they both get a rank of 1.5. You can customize the ranking behavior using the method parameter. One useful option is method='dense', which assigns the same rank to ties but doesn't leave gaps in the ranking sequence. This is helpful when you want a clean, consecutive ranking system without skips.

- ```df["Rank"] = df["Score"].rank()``` # Default: average method
- ```df["Rank"] = df["Score"].rank(method="dense")``` # 1, 2, 2, 3
- ```df["Rank"]``` = df["Score"].rank(ascending=False)```

In [7]:
df2['Rank'] = df2["IMDb"].rank(method= "dense")
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
4,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0
5,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0
6,Hrithik Roshan,War,2019,Action,475,6.5,5.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0

### Renaming Columns & Index

- ```df.rename(columns={"oldName": "newName"}, inplace=True)```
- ```df.rename(index={0: "row1", 1: "row2"}, inplace=True)```

In [8]:
df2.rename(columns = {"Rank":"RANK"}, inplace= True)
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,RANK
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
4,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0
5,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0
6,Hrithik Roshan,War,2019,Action,475,6.5,5.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0

### To rename all columns:

In [9]:
# df2.columns = ["Actor", "Film", "Year", "Genre", "BoxOffice(INR Crore)", "IMDb","RANK"]
# df2

### Changing Column Order
- Just pass a new list of column names:

In [12]:
df3 = df2[["Film", "Genre", "Actor", "RANK", "IMDb", "Year", "BoxOffice(INR Crore)"]]

df3

,Film,Genre,Actor,RANK,IMDb,Year,BoxOffice(INR Crore)
0,Dangal,Biography,Aamir Khan,11.0,8.4,2016,2024
1,Tiger Zinda Hai,Action,Salman Khan,3.0,6.0,2017,565
2,Badrinath Ki Dulhania,Romantic Comedy,Varun Dhawan,4.0,6.1,2017,201
3,Padmaavat,Historical,Ranveer Singh,6.0,7.0,2018,585
4,Andhadhun,Thriller,Ayushmann Khurrana,10.0,8.3,2018,111
5,Stree,Horror Comedy,Rajkummar Rao,8.0,7.5,2018,180
6,War,Action,Hrithik Roshan,5.0,6.5,2019,475
7,Good Newwz,Comedy,Akshay Kumar,6.0,7.0,2019,318
8,Uri: The Surgical Strike,Action,Vicky Kaushal,9.0,8.2,2019,342
9,Brahmastra,Fantasy,Ranbir Kapoor,1.0,5.6,2022,431
10,Bhool Bhulaiyaa 2,Horror Comedy,Kartik Aaryan,2.0,5.9,2022,266
11,Pathaan,Action,Shah Rukh Khan,7.0,7.2,2023,1050

### Summary
- Sort, rank, and rename to prepare your data
- Reordering and reshaping are key for EDA and visualization