## Getting Started with Pandas

### What is Pandas?
Pandas is a powerful, open-source Python library used for data manipulation,
cleaning, and analysis. It provides two main data structures:
- Series: A one-dimensional labeled array
- DataFrame: A two-dimensional labeled table (like an Excel sheet or SQL table)
  
Pandas makes working with structured data fast, expressive, and flexible.

- If you’re working with tables, spreadsheets, or CSVs in Python—Pandas is
your best friend

### Why Use Pandas?
| Task                | Without Pandas                     | With Pandas                  |
|---------------------|------------------------------------|------------------------------|
| Load a CSV          | open() + loops                     | pd.read_csv()                |
| Filter rows         | Custom loop logic                  | df[df["col"] > 5]            |
| Group & summarize   | Manual aggregation                 | df.groupby()                 |
| Merge two datasets  | Nested loops                       | pd.merge()                   |

### Pandas vs Excel vs SQL vs NumPy
| Tool   | Strengths                              | Weaknesses                          |
|:-------|:----------------------------------------|:--------------------------------------|
| Excel  | Easy UI, great for small data          | Slow, manual, not scalable           |
| SQL    | Efficient querying of big data         | Not ideal for transformation logic   |
| NumPy  | Fast, low-level array operations       | No labels, harder for tabular data   |
| Pandas | Label-aware, fast, flexible            | Slightly steep learning curve        |

- Pandas bridges the gap between NumPy performance and Excel-like usability.
Pandas is built on top of NumPy

#### Summary
- Use Pandas when working with structured data.
- It’s the Swiss Army knife of data science.

### Core Data Structures in Pandas
Pandas is built on two main data structures:
- Series → One-dimensional (like a single column in Excel)
- DataFrame → Two-dimensional (like a full spreadsheet or SQL table)

#### Series — 1D Labeled Array
- A Series is like a list with labels (index).

In [1]:
import pandas as pd
s= pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

###### ***Notice:*** the automatic index: 0, 1, 2, 3

You can also define a custom index:|

In [2]:
import pandas as pd
s = pd.Series([10,20,30,40],index = ["a","b","c","d"])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

- A pandas.Series may look similar to a Python dictionary because both store data
with labels, but a Series offers much more. Unlike a dictionary, a Series supports
fast vectorized operations, automatic index alignment during arithmetic, and
handles missing data using NaN . It also allows both label-based and positionbased access, and integrates seamlessly with the pandas ecosystem, especially
DataFrames. While a dictionary is great for simple key–value storage, a Series is
better suited for data analysis and manipulation tasks where performance,
flexibility, and built-in functionality matter.

## DataFrame — 2D Labeled Table
- A DataFrame is like a dictionary of Series — multiple columns with labels.

In [3]:
import pandas as pd
data = {
    "Name":["Manish","Govind","Hemant"],
    "Age":[22,23,20],
    "City":["Gr-Noida","jewar","Aligarh"]
}
df = pd.DataFrame(data)
print(type(df))           # show the type of data
df

<class 'pandas.core.frame.DataFrame'>

     Name  Age      City
0  Manish   22  Gr-Noida
1  Govind   23     jewar
2  Hemant   20   Aligarh

- ***Note:*** Each column in a DataFrame is a Series .

#### Index and Labels
Every Series and DataFrame has an Index — it helps with:
- Fast lookups
- Aligning data
- Merging & joining
- Time series operations

In [4]:
# Creating DataFrame using dictionary
import pandas as pd
data = {
    "name":["Manish","Govind","Hemant"],
    "age":[22,23,20],
    "city":["Gr-Noida","jewar","Aligarh"]
}
df = pd.DataFrame(data)
df.index         # Row labels

RangeIndex(start=0, stop=3, step=1)

In [5]:
df.columns    # column labels

Index(['name', 'age', 'city'], dtype='object')

 ### You an change them (index column) using:

In [6]:
df.index = ["a","b","c"]
print(df)

     name  age      city
a  Manish   22  Gr-Noida
b  Govind   23     jewar
c  Hemant   20   Aligarh

In [7]:
df.columns = ["Name", "Age", "City"]
print(df)

     Name  Age      City
a  Manish   22  Gr-Noida
b  Govind   23     jewar
c  Hemant   20   Aligarh

## Creating DataFrames
- Let’s look at different ways to create a Pandas DataFrame — the core data
structure you’ll be using 90% of the time in data science.

#### 1.From Python Lists

In [8]:
import pandas as pd
data= [
    ["Alice",25],
    ["Bob",30],
    ["Charlie",35]
]

df = pd.DataFrame(data,columns=["Name","Age"])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

#### 2. From Dictionary Of List
- Most common and readable format:

In [9]:
import pandas as pd
data = {
    "Name":["Manish","Govind","Akshay"],
    "Age":[23,24,25],
    
}
pf = pd.DataFrame(data)
pf

     Name  Age
0  Manish   23
1  Govind   24
2  Akshay   25

- Each key becomes a column, and each list is the column data.

### 3. From Numpy Arrays

In [10]:
import numpy as np
import pandas as pd
arr = np.array([[1,2],[3,4]])
df = pd.DataFrame(arr)
df

   0  1
0  1  2
1  3  4

### 4.From CSV Files

In [11]:
import pandas as pd
df = pd.read_csv('02_data.csv')
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

- Use options like: - sep , header , names , index_col , usecols , nrows , etc

In [12]:
#Example
import pandas as pd
df = pd.read_csv('02_data.csv', usecols = ['Actor','Film'])
df

                 Actor                      Film
0       Shah Rukh Khan                   Pathaan
1          Salman Khan           Tiger Zinda Hai
2           Aamir Khan                    Dangal
3        Ranbir Kapoor                Brahmastra
4        Ranveer Singh                 Padmaavat
5   Ayushmann Khurrana                 Andhadhun
6        Rajkummar Rao                     Stree
7       Hrithik Roshan                       War
8         Akshay Kumar                Good Newwz
9        Kartik Aaryan         Bhool Bhulaiyaa 2
10        Varun Dhawan     Badrinath Ki Dulhania
11       Vicky Kaushal  Uri: The Surgical Strike

In [13]:
import pandas as pd
df = pd.read_csv("02_data.csv", nrows=3)
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

### 5. From Excel

In [14]:
import pandas as pd
pf = pd.read_excel('02 _Student_Data.xlsx')
pf

     Name  Age  Marks
0    Amit   20     78
1    Ravi   21     85
2   Sneha   19     92
3   Priya   22     67
4   Karan   20     74
5  Anjali   21     88
6   Vikas   23     59
7    Neha   20     81
8   Rahul   22     73
9   Pooja   19     90

###  6. From JSON

In [15]:
import pandas as pd
df = pd.read_json('02_Data.json')
df

   id    name  age  marks    city
0   1    Amit   20     78   Delhi
1   2    Ravi   21     85  Mumbai
2   3   Sneha   19     92   Delhi
3   4   Priya   22     67    Pune
4   5   Karan   20     74  Mumbai
5   6  Anjali   21     88   Delhi
6   7   Vikas   23     59    Pune

### From SQL Databases

In [16]:
# import sqlite3
# conn = sqlite.connect('mydb.sqlite')
# df = pd.read_sql("SELECT * FROM USER",conn)

_IncompleteInputError: incomplete input (778552090.py, line 3)

#### ***NOTE:*** Can also read from a URL or string.

In [ ]:
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'
import pandas as pd
df=  pd.read_csv(url)
df

## EDA (Exploratory Data Analysis)

###### Exploratory Data Analysis (EDA) is an essential first step in any data science project.
- It involves taking a deep look at the dataset to understand its structure, spot
patterns, identify anomalies, and uncover relationships between variables. This
process includes generating summary statistics, checking for missing or duplicate
data, and creating visualizations like histograms, box plots, and scatter plots. The
goal of EDA is to get a clear picture of what the data is telling you before applying
any analysis or machine learning models.

- By exploring the data thoroughly, you can make better decisions about how to
clean, transform, and model it effectively.

Once your DataFrame is ready, run these to understand your data:

- df.head() # First 5 rows
- df.tail() # Last 5 rows
- df.info() # Column info: types, non-nulls
- df.describe() # Stats for numeric columns
- df.columns # List of column names
- df.shape # (rows, columns)

- lets check it

In [3]:
import pandas as np
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'
df =  np.read_csv(url)
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [7]:
df.describe()                       # very import function

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [8]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
df.shape

(244, 7)

### **Data Selection & Filtering**
- Selecting the right rows and columns is the first step in analyzing any dataset.
Pandas gives you several powerful ways to do this

In [10]:
import pandas as pd
df = pd.read_csv('03_data.csv')
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

#### Selecting Rows & Columns
###### Selecting Columns
- df["column_name"]           # Single column (as Series)
- df[["col1", "col2"]]       # Multiple columns (as DataFrame)

In [11]:
df["Actor"]

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [12]:
df[['Actor','IMDb']]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

##### Selecting Rows by Index
- Use .loc[] (label-based) and .iloc[] (position-based)

In [13]:
df.loc[0]                                  # label wise accessing

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [14]:
df.loc[[1,2]]

         Actor             Film  Year      Genre  BoxOffice(INR Crore)  IMDb
1  Salman Khan  Tiger Zinda Hai  2017     Action                   565   6.0
2   Aamir Khan           Dangal  2016  Biography                  2024   8.4

##### Select Specific Rows and Columns

In [15]:
df.loc[0,"Actor"]

'Shah Rukh Khan'

In [16]:
df.iloc[1,0]                                # acess by row and column indices

'Salman Khan'

In [17]:
df.loc[5,'Film']

'Andhadhun'

##### You can also slice:

In [18]:
df.loc[0:2,['Actor','Film']]

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai
2      Aamir Khan           Dangal

In [19]:
df.iloc[0:3,0:2]

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai
2      Aamir Khan           Dangal

In [20]:
df.iloc[0:3,-1]

0    7.2
1    6.0
2    8.4
Name: IMDb, dtype: float64

##### Fast Access: .at and .iat
- These are optimized for single element access:

In [21]:
df.at[0,"Actor"]

'Shah Rukh Khan'

In [22]:
df.at[3,"Film"]

'Brahmastra'

In [23]:
df.iat[1,3]

'Action'

In [24]:
df.iat[4,2]

np.int64(2018)

#### Filtering with Conditions
-  simple conditions

In [25]:
df[df["Year"]>2018]                           # filter with respect to year of data

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [27]:
df[df["Actor"]=='Akshay Kumar']

          Actor        Film  Year   Genre  BoxOffice(INR Crore)  IMDb
8  Akshay Kumar  Good Newwz  2019  Comedy                   318   7.0

### Multiple Conditions (AND / OR)
note:Use parentheses around each condition!

In [28]:
df[(df['Year']>2018) & (df['IMDb']>6)]        # multiple conditions

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

### Querying with .query()
- The .query() method in pandas lets you filter DataFrame rows using a string
expression — it’s a more readable and often more concise alternative to using
boolean indexing.
- This is a cleaner, SQL-like way to filter:

In [29]:
df.query("Year == 2018 and IMDb > 7 ")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5

In [30]:
df.query("IMDb > 6 and Actor == 'Akshay Kumar' ")

          Actor        Film  Year   Genre  BoxOffice(INR Crore)  IMDb
8  Akshay Kumar  Good Newwz  2019  Comedy                   318   7.0

#### 3. Use backticks for column names with spaces or special characters

In [32]:
# df.query("`first name` == 'Alice'")

#### 4. You can use @ to reference Python variables
- To pass external variables into .query() :

In [33]:
Year = 2018
df.query("Year > @Year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

#### Summary
- Use df[col] , .loc[] , .iloc[] , .at[] , .iat[] to access data
- Filter with logical conditions or .query() for readable code
- Mastering selection makes the rest of pandas feel easy

## Data Cleaning & Preprocessing
- Real-world data is messy. Pandas gives us powerful tools to clean and transform
data before analysis.

### Handling Missing Values
- ```df.isnull()``` # True for NaNs
- ```df.isnull().sum()``` # Count missing per column

In [34]:
import pandas as pd
df = pd.read_csv('04_data_cleaning_sample.csv')
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [20]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

### Drop Missing Data

- ```df.dropna()``` # Drop rows with *any* missing values
- ```df.dropna(axis=1)``` # Drop columns with missing values

In [21]:
df.dropna()                      #ye row drop krega(Delete) jimse missing value hogy

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [22]:
df.dropna(axis=1)                       #ye column drop(delete) krega jimse missing value hogy

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

## Fill Missing Data
- In pandas, fillna is used to fill unknown values. ffill and bfill are methods used to fill
missing values (like NaN, None, or pd.NA) by propagating values forward or
backward.

| Method       | Purpose                          |
| ------------ | -------------------------------- |
| fillna(0)    | Replace NaN with fixed value     |
| fillna(mean) | Replace with statistical value   |
| ffill()      | Forward propagate previous value |
| bfill()      | Backward propagate next value    |

In [23]:
df.fillna(0)                # replcae Nan with 0

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [24]:
df['Age'].fillna(df['Age'].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [26]:
df.ffill()                   # fiill from top to down

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [27]:
df.bfill()                   # fiill from  down to top

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

### Detecting & Removing Duplicates
- ```df.duplicated()``` returns a boolean Series where: True means that row is a duplicate
                       of a previous row. False means it’s the first occurrence (not a duplicate yet).

- ```df.duplicated()``` # True for duplicates
- ```df.drop_duplicates()``` # Remove duplicate rows

In [28]:
df.duplicated()                   # True for duplicates

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [29]:
df.drop_duplicates()       # Remove duplicate rows

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

-  ```Note:``` duplcate remove krne ke baad indecis ka format change ho jaata haia upr output me dekh le

#### Check based on specific columns:

In [33]:
# df
df.duplicated(subset = ["Name","Age"]) #pair ke baase pr duplicate remove krega

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

```Note:``` Nan ko equal treat kiya jata hai incase of duplication method

### String Operations with .str
- Works like vectorized string methods and returns a pandas Series:

- ```df["Name"].str.lower()``` # Converts all names to lowercase.
- ```df["City"].str.contains("delhi", case=False)``` # Checks if 'delhi' is in the city
         name, case-insensitive.
- ```df["Email"].str.split("@")``` # Outputs a pandas Series where each element is a list of strings (the split parts). This is where a Python list comes into play, but the
     outer object is still a pandas Series.

In [35]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [41]:
df["City"].str.contains("delhi", case=False)     # return pandas series

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

```Note:``` ```(case = false)``` : iska mtlb ha casesensitve false hai

### Type Conversions with .astype()
- Convert column data types:
- ```df["Age"] = df["Age"].astype(int)```
- ``` df["Date"] = pd.to_datetime(df["Date"])```
- ```df["Category"] = df["Category"].astype("category")```

In [45]:
import pandas as pd
df = pd.read_csv('04_data_cleaning_sample.csv')
df2 = df.dropna().copy()
df2["Age"] = df2["Age"].astype(int)
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

### Applying Functions

- .apply() → Apply any function to rows or columns

In [48]:
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x >= 18 else "Minor")
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Adult
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

- .map() → Element-wise mapping for Series

In [65]:
gender_map = {"M": "Male", "F": "Female"}
df2["Gender"] = df2["Gender"].map(gender_map)
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York    NaN  alice@example.com  01-05-2021
2    Bob   30  Los Angeles    NaN    bob@example.com  15-06-2020
4  David   22       Mumbai    NaN  david@example.com  12-11-2019
6  Alice   25     New York    NaN  alice@example.com  01-05-2021
7  Alice   25     New York    NaN  alice@example.com  01-05-2021

- .replace() → Replace specific values

In [66]:
df2["City"] = df2["City"].replace({"Mumbai":"MUMBAI","New York":"NEW  YORK"})
df2

    Name  Age         City Gender              Email   Join Date
0  Alice   25    NEW  YORK    NaN  alice@example.com  01-05-2021
2    Bob   30  Los Angeles    NaN    bob@example.com  15-06-2020
4  David   22       MUMBAI    NaN  david@example.com  12-11-2019
6  Alice   25    NEW  YORK    NaN  alice@example.com  01-05-2021
7  Alice   25    NEW  YORK    NaN  alice@example.com  01-05-2021

#### Summary
- Use isnull() , fillna() , dropna() for missing data
- Clean text with .str , convert types with .astype()
- Use apply() , map() , replace() to transform your columns
- Data cleaning is where 80% of your time goes in real projects